//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLFindInTables2
{
    using System;
    using System.Collections.Generic;
    
    public partial class GarthDeviceInfo2
    {
        public int ID { get; set; }
        public string company { get; set; }
        public string device { get; set; }
        public string module { get; set; }
        public string serialNumber { get; set; }
        public string IPAddress { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string position { get; set; }
    }
}
